/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Cart } from './cart';


export interface CartItem { 
    id?: number;
    product?: Product;
    cart?: Cart;
    quantity?: number;
}

