/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Cart } from './cart';


export interface User { 
    id?: number;
    name?: string;
    email?: string;
    cart?: Cart;
}

